name: Deploy OpenAPI Specifications to AWS API Gateway

on:
  workflow_run:
    workflows: ["Lint OpenAPI Specifications", "Validate OpenAPI Specifications"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CENTRAL_SEQUENCE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CENTRAL_SEQUENCE_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy OpenAPI spec to AWS API Gateway
        run: aws apigateway import-rest-api --body file://api/openapi.yml
