name: Validate OpenAPI Specifications

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install yq and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:rmescandon/yq -y
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Convert OpenAPI YAML to JSON
        run: |
          yq eval -o=json api/openapi.yml > api/openapi.json
          echo "Converted OpenAPI spec to JSON."

      - name: Validate OpenAPI JSON
        run: |
          jq . api/openapi.json

      - name: Base64 Encode OpenAPI JSON
        run: |
          cat api/openapi.json | base64 > api/openapi_base64.json
          echo "Base64 encoded OpenAPI JSON."

      - name: Import OpenAPI spec to AWS API Gateway
        run: |
          aws apigateway import-rest-api --body file://api/openapi_base64.json
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Check AWS API Gateway Import Result
        if: failure()
        run: |
          echo "AWS API Gateway import failed. Please check the OpenAPI spec."
          exit 1
