name: Validate OpenAPI Specifications with AWS API Gateway

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials using secrets stored in GitHub
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CENTRAL_SEQUENCE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CENTRAL_SEQUENCE_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Install yq to handle YAML to JSON conversion
      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt-get update
          sudo apt-get install -y yq

      # Step 4: Convert OpenAPI YAML to JSON for AWS CLI compatibility
      - name: Convert YAML to JSON
        run: yq eval -o=json api/openapi.yml > api/openapi.json

      # Step 5: Base64 encode the OpenAPI JSON
      - name: Base64 encode the OpenAPI JSON
        run: |
          cat api/openapi.json | base64 > api/openapi_base64.json

      # Step 6: Import the OpenAPI specification to AWS API Gateway
      - name: Validate and Import OpenAPI Spec to AWS API Gateway
        run: |
          aws apigateway import-rest-api --body file://api/openapi_base64.json
